#!/usr/bin/env bash

export SCRIPT_ROOT="$(dirname "${BASH_SOURCE}")"
source $SCRIPT_ROOT/variables.sh

oc new-app --param=MONGODB_FHSUPERCORE_PASSWORD="$MONGO_PASSWORD",REDIS_PASSWORD="$REDIS_PASSWORD",FH_MESSAGING_API_KEY="$MESSAGING_API_KEY",FH_METRICS_API_KEY="$METRICS_API_KEY",FH_MILLICORE_API_KEY="$MILLICORE_API_KEY",FH_MILLICORE_SERVICE_KEY="$MILLICORE_SERVICE_KEY",MONGODB_FHAAA_PASSWORD="$MONGO_PASSWORD",GITLAB_MILLICORE_SERVICE_KEY="$GITLAB_MILLICORE_SERVICE_KEY" -f "${TEMPLATES_DIR}/generated/fh-core-backend.json"
