#!/usr/bin/env bash

export SCRIPT_ROOT="$(dirname "${BASH_SOURCE}")"

source $SCRIPT_ROOT/variables.sh

#setup appstore, millicore, apache, ngui

oc new-app --param=FH_NGUI_IMAGE_VERSION="$VERSION_NGUI",HTTPD_IMAGE_VERSION="$VERSION_HTTPD",CLUSTER_HOST="$CLUSTER_HOST",MILLICORE_IMAGE_VERSION="$VERSION_MILLICORE",FH_APPSTORE_IMAGE_VERSION="$VERSION_APPSTORE",FH_MESSAGING_API_KEY="$MESSAGING_API_KEY",FH_MILLICORE_API_KEY="$SUPERCORE_API_KEY" -f "${TEMPLATES_DIR}/generated/fh-core-frontend.json"
