#!/usr/bin/env bash

#set up mysql mongo memcached

source ./common.sh

oc new-app --param=MONGODB_IMAGE_VERSION="$VERSION_MONGO",MEMCACHED_IMAGE_VERSION="$VERSION_MEMCACHED",REDIS_IMAGE_VERSION="$VERSION_REDIS",MONGODB_SERVICE_NAME="$MONGO_SERVICE_NAME",MONGODB_FHAAA_PASSWORD="${MONGO_PASSWORD}",MONGODB_FHSUPERCORE_PASSWORD="$MONGO_PASSWORD",MONGODB_FHREPORTING_PASSWORD="$MONGO_PASSWORD",MYSQL_USER="$MCORE_MYSQL_USER",MYSQL_PASSWORD="$MCORE_MYSQL_PASSWORD",MYSQL_DATABASE="$MCORE_MYSQL_DB" -f "${TEMPLATES_DIR}/generated/fh-core-infra.json"
